package app.aaps.plugins.aps.openAPSFCL.vnext.analyzer

import app.aaps.plugins.aps.openAPSFCL.vnext.database.FCLCycleLogEntity
import java.time.Instant

/**
 * Zet FCLCycleLogEntity (Room database) om naar LogRow (analyzer domeinmodel).
 * prebolus velden bestaan niet meer in FCLvNext en zijn verwijderd.
 */
fun FCLCycleLogEntity.toLogRow(): LogRow = LogRow(
    timestamp              = Instant.ofEpochMilli(timestampMs),
    bg                     = bg,
    target                 = target,
    deltaTarget            = bg - target,
    iob                    = iob,
    iobRatio               = iobRatio,
    slope                  = slope,
    accel                  = accel,
    recentSlope            = recentSlope,
    recentDelta5m          = recentDelta5m,
    consistency            = consistency,
    predictedPeak          = predictedPeak.takeIf { it > 0.0 },
    mealEpisodeId          = mealEpisodeId.takeIf { it >= 0 },
    minutesSinceMealStart  = minutesSinceMealStart.takeIf { it >= 0 },
    riseSinceMealStart     = riseSinceMealStart.takeIf { it > 0.0 },
    finalDose              = finalDose,
    deliveredTotal         = deliveredTotal,
    shouldDeliver          = shouldDeliver,
    mealState              = mealState,
    earlyConfidence        = earlyConfidence,
    earlyTargetU           = earlyTargetU,
    decisionReason         = decisionReason,
    watchingFrontloadTriggered = watchingFrontloadTriggered,
    watchingFrontloadTargetU   = watchingFrontloadTargetU,
    commitAllowed          = commitAllowed,
    effectiveCommitAllowed = effectiveCommitAllowed,
    commitDoseRaw          = commitDoseRaw,
    commitDoseFinal        = commitDoseFinal,
    hypoActive             = hypoActive,
    hypoProjectedBg        = hypoProjectedBg,
    topGuardActive         = topGuardActive,
    topGuardCapFactor      = topGuardCapFactor,
    trajectoryHardBlock    = trajectoryHardBlock,
    sterktePct             = sterktePct,
    timingPct              = timingPct,
    volhoudendheidPct      = volhoudendheidPct,
    nachtFactorPct         = nachtFactorPct,
    doseDistribution       = doseDistributionStyle,
    nightResponseStyle     = nightResponseStyle,
    peakIobBrakeActive     = peakIobBrakeActive,
    peakApproachFactor     = peakApproachFactor,
    suppressForPeak        = suppressForPeak,
    peakState              = peakState,
    suppressReason         = suppressReason,
    lockoutReason          = lockoutReason,
    commitBlockReason      = commitBlockReason,
    iobMarginToBrake       = iobMarginToBrake,
    iobMarginToLockout     = iobMarginToLockout,
    predMarginToWatching   = predMarginToWatching,
    predMarginToTarget     = predMarginToTarget,
    slopeMarginToBrake     = slopeMarginToBrake,
    predictedPeakBallistic = predictedPeakBallistic,
    futureDrop60           = futureDrop60,
    peakFloorActive        = peakFloorActive,
    peakFloorValue         = peakFloorValue,
    hEff                   = hEff,
    iobScaleUsed           = iobScaleUsed,
    vUsed                  = vUsed,
    peakMaxSlope           = peakMaxSlope,
    iobHeadroom            = iobHeadroom,
    doseSuppressedU        = doseSuppressedU,
    peakApproachActive     = peakApproachActive,
    earlyResetThisCycle    = earlyResetThisCycle,
    downtrendLocked        = downtrendLocked,
    sensorBlipActive       = sensorBlipActive,
    earlyBoostActive       = earlyBoostActive,
    earlyBoostCount        = earlyBoostCount,
    earlyBoostFactor       = earlyBoostFactor,
    guardMaxSmbLimited     = guardMaxSmbLimited,
    episodeCommitNr        = episodeCommitNr
)