import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Writes the FCLvNext update-checker and CSV-upload secrets as a small generated Kotlin object.
 *
 * ## Why this exists
 *
 * `:plugins:aps` is a Kotlin Multiplatform module (`kotlin { android { ... } }`), not a classic
 * `com.android.library` module - the two Android Gradle Plugin entry points cannot be combined
 * (see the comment at the top of this module's build.gradle.kts). The KMP android target has no
 * `buildFeatures { buildConfig = true }` / `defaultConfig { buildConfigField(...) }` - those are
 * classic-AGP-only APIs, so `BuildConfig` does not exist here.
 *
 * [GenerateBuildInfoTask] already solved the same shaped problem for the desktop/iOS version
 * string: generate a plain Kotlin `object` with `const val` fields instead of relying on
 * `BuildConfig`. This task does the same for the FCL secrets, which are read out of
 * `local.properties` (never committed) so they never appear in source control.
 *
 * Missing values simply become empty strings here, exactly like `BuildConfig`'s string fields
 * would default to `""` - `FclUpdateChecker`/`FclCsvUploader` already treat an empty value as
 * "not configured" and fall back gracefully, no crash.
 */
abstract class GenerateFclSecretsTask : DefaultTask() {

    @get:Input
    abstract val driveUpdateFolderId: Property<String>

    @get:Input
    abstract val driveUpdateApiKey: Property<String>

    @get:Input
    abstract val csvUploadUrl: Property<String>

    @get:Input
    abstract val csvUploadSecret: Property<String>

    /** Package for the generated object. */
    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        driveUpdateFolderId.convention("")
        driveUpdateApiKey.convention("")
        csvUploadUrl.convention("")
        csvUploadSecret.convention("")
    }

    @TaskAction
    fun generate() {
        val dir = outputDir.get().asFile
        dir.deleteRecursively()
        val pkg = packageName.get()
        val file = File(dir, pkg.replace('.', '/') + "/GeneratedFclSecrets.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by GenerateFclSecretsTask from local.properties. Do not edit.
            |// Never commit real values here - this file is generated fresh on every build, and
            |// local.properties itself stays out of version control.
            |
            |package $pkg
            |
            |/**
            | * FCL update-checker and CSV-upload secrets, read from `local.properties` at build time.
            | *
            | * Stands in for `BuildConfig`, which this Kotlin Multiplatform module does not have (see
            | * the kdoc on `GenerateFclSecretsTask`). An empty string means "not configured" - the
            | * callers already handle that without crashing.
            | */
            |object GeneratedFclSecrets {
            |
            |    const val FCL_UPDATE_DRIVE_FOLDER_ID: String = "${driveUpdateFolderId.get()}"
            |    const val FCL_UPDATE_DRIVE_API_KEY: String = "${driveUpdateApiKey.get()}"
            |    const val FCL_CSV_UPLOAD_URL: String = "${csvUploadUrl.get()}"
            |    const val FCL_CSV_UPLOAD_SECRET: String = "${csvUploadSecret.get()}"
            |}
            |
            """.trimMargin()
        )
    }
}
